# Exercícios

## Parte 1: vetorização
1. Faça uma função que receba dois arrays como parâmetro e calcule o **MSE (mean squared error)** entre eles
2. Faça uma função que receba dois arrays como parâmetro e calcule o **MAE (mean absoluted error)** entre eles

In [2]:
import numpy as np

In [9]:
def mse_calc( arr1, arr2):
    arr_dif = arr1 - arr2
    arr_dif = np.power(arr_dif,2)
    print(arr_dif.mean())


In [21]:
arr1 = np.array([2,2,3])
arr2 = np.array([0,2,3])

mse_calc(arr1, arr2)

1.3333333333333333


In [22]:
def mae_calc( arr1, arr2):
    arr_dif = arr1 - arr2
    arr_dif = np.abs(arr_dif)
    print(arr_dif.mean())

In [23]:
mae_calc(arr1, arr2)

0.6666666666666666


## Parte 2: carregando arquivos e usando a lib
1. Dentro da pasta `dados` existe um arquivo chamado `metricas.rar`. Nesse `.rar` você encontra uma série de arquivos `.dat` que pussui resultados de diferentes métricas. Seu objetivo aqui é carregar todos esses arquivos e calcular a matriz de correlação entre as métricas.

**Dicas:**
- Você conhece a matriz de correlação? Não? Estou sugiro que leia [esse post para entender mais sobre](https://datascience.eu/pt/matematica-e-estatistica/o-que-e-uma-matriz-de-correlacao/) ou veja [este vídeo](https://www.youtube.com/watch?v=JVVBaW14s0U)
- Não sabe o que usar na NumPy? De uma olhada na [documentação](https://numpy.org/doc/stable/reference/routines.html)

In [3]:
import rarfile
import os
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

path_metricas_rar = "/home/thiago_lahass/Documents/IA - UFES/Modulo II - Ferramentas/2_numpy_scipy/data/metricas.rar"
path_metricas_destino = "data/metricas"

# Extrair os arquivos .dat do arquivo .rar
# with rarfile.RarFile(path_metricas_rar, 'r') as rar_ref:
#     rar_ref.extractall(path=path_metricas_destino)

# Listar arquivos .dat na pasta de destino
arquivos_dat = [os.path.join(path_metricas_destino, arquivo) for arquivo in os.listdir(path_metricas_destino) if arquivo.endswith('.dat')] 

# Calcular a matriz de correlação
matriz_metricas = np.ndarray

print(len(arquivos_dat))

# Carregar dados do arquivo .dat em um DataFrame
df = pd.read_csv(arquivos_dat[0], sep=' ')  # Assumindo que os dados estão separados por tabulação
    
# print(df)

print(type(df.values.T))

for i in range(5):
    # Carregar dados do arquivo .dat em um DataFrame
    df = pd.read_csv(arquivos_dat[i], sep=' ')  # Assumindo que os dados estão separados por tabulação
    
    # Adicionar à lista de matrizes de correlação
    np.append(matriz_metricas, df.T)

# for arquivo_dat in arquivos_dat:
#     # Carregar dados do arquivo .dat em um DataFrame
#     df = pd.read_csv(arquivo_dat, sep='\t')  # Assumindo que os dados estão separados por tabulação
    
#     # Adicionar à lista de matrizes de correlação
#     matriz_metricas.append(df.values.T)

print(matriz_metricas)

# Calcular a matriz de covariância
# cov_matrix = np.cov(matriz_metricas)

# Calcular a matriz de correlação a partir da matriz de covariância
correlation_matrix = np.corrcoef(matriz_metricas)

# print("Matriz de Covariância:")
# print(cov_matrix)

# print("\nMatriz de Correlação:")
# print(correlation_matrix)

37
<class 'numpy.ndarray'>
a <class 'numpy.ndarray'>
teste, <class 'type'>
<class 'numpy.ndarray'>


TypeError: unsupported operand type(s) for /: 'type' and 'int'

In [42]:
data = np.array([
    [1, 2, 3, 4],  # Métrica1
    [2, 4, 6, 8],  # Métrica2
    [3, 6, 9, 12],  # Métrica3
    [4, 8, 12, 16]  # Métrica4
])

print(data)

# Calcular a matriz de covariância
cov_matrix = np.cov(data)

# Calcular a matriz de correlação a partir da matriz de covariância
correlation_matrix = np.corrcoef(data)

print("Matriz de Covariância:")
print(cov_matrix)

print("\nMatriz de Correlação:")
print(correlation_matrix)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Matriz de Covariância:
[[ 1.66666667  3.33333333  5.          6.66666667]
 [ 3.33333333  6.66666667 10.         13.33333333]
 [ 5.         10.         15.         20.        ]
 [ 6.66666667 13.33333333 20.         26.66666667]]

Matriz de Correlação:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
