# Subpacotes e outros métodos
- Numpy possui diversos subpacotes e centenas de métodos para lidar com diferentes problemas
- Aqui vamos explorar com métodos para matemática básica, algebra linear, e números aleatórios
- Porém, [nesta parte da documentação](https://numpy.org/doc/stable/reference/routines.html), você encontra um referência para tudo que tem disponível na linguagem

In [65]:
import numpy as np

## Funções para matemática básica
- Caso você tenha que lidar com matemática básica, a Numpy oferece uma gama de operações já implementada
- Vamos explorar algumas delas
- Um referência para todas elas pode ser [encontrada aqui](https://numpy.org/doc/stable/reference/routines.math.html)

### Trigonometria
- Podemos calcular seno, cosseno e tangente de maneira muito fácil

In [67]:
np.pi

3.141592653589793

In [66]:
np.sin(np.pi/2)

1.0

In [68]:
np.cos(np.pi)

-1.0

In [69]:
np.tan(np.deg2rad(45))

0.9999999999999999

- Vamos implementar a relação:

$$tag (x) = \frac{sen(x)}{cos(x)} $$

In [70]:
np.sin(np.deg2rad(45)) / np.cos(np.deg2rad(45))

0.9999999999999999

### Arredondamento

In [71]:
np.round(1.49)

1.0

In [72]:
np.round(1.5)

2.0

In [73]:
x = np.array([1.1, 1.2, 1.5, 1.3, 1.9])
np.round(x)

array([1., 1., 2., 1., 2.])

In [74]:
np.floor(x)

array([1., 1., 1., 1., 1.])

In [75]:
np.ceil(x)

array([2., 2., 2., 2., 2.])

### Somatório, produtório e outros

In [76]:
y = np.array([1, 2, 3, 4])
np.prod(y)

24

In [77]:
np.sum(y)

10

In [78]:
np.cumsum(y)

array([ 1,  3,  6, 10])

In [79]:
np.cumprod(y)

array([ 1,  2,  6, 24])

In [80]:
np.exp(y)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [81]:
np.log(y)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [82]:
np.mod(y, 2)

array([1, 0, 1, 0])

___

## Algebra linear
- NumPy possui diversas funções para lidar com conceitos da algebra linear
- Você pode consultar todas as funções disponíveis dentro do subpacote [np.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg)

In [83]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 2, 2, 2])
z = np.array([3, 3, 3, 3, 3,])
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 2], [2, 2]])
C = np.array([[3, 3, 3], [3, 3, 3], [3, 3, 3]])

- Produto interno

In [84]:
np.dot(x, y)

20

In [85]:
np.dot(x, 2)

array([2, 4, 6, 8])

In [86]:
np.dot(x, z)

ValueError: shapes (4,) and (5,) not aligned: 4 (dim 0) != 5 (dim 0)

- Multiplicação de matriz

In [87]:
np.matmul(A, B)

array([[ 6,  6],
       [14, 14]])

In [88]:
A @ B

array([[ 6,  6],
       [14, 14]])

In [89]:
A @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

___
**Tarefa pra casa:**

- Qual a diferença entre `np.matmul` e `np.dot`?
____

- Auto vetor

In [90]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

- Auto valor

In [91]:
np.linalg.eigvals(A)

array([-0.37228132,  5.37228132])

- Norma:

In [92]:
np.linalg.norm(x)

5.477225575051661

In [93]:
np.linalg.norm(C)

9.0

- Determinante de uma matriz

In [94]:
np.linalg.det(A)

-2.0000000000000004

- Inversa de uma matriz

In [95]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Números aleatórios
- Podemos gerar números (pseudo) aleatórios usando o subpacote `np.random`

- Gerando números entre zero e um

In [98]:
np.random.rand()

0.34728994955959414

In [99]:
np.random.rand(4)

array([0.07239254, 0.49278166, 0.0011501 , 0.44283452])

In [101]:
np.random.rand(4, 4)

array([[0.51235159, 0.73079654, 0.49230869, 0.44666636],
       [0.11801164, 0.21411342, 0.53502078, 0.28919946],
       [0.90596435, 0.20253003, 0.62077527, 0.255886  ],
       [0.74811003, 0.00222474, 0.66208754, 0.20967211]])

- Gerando números de uma distribuição normal (média zero e desvio padrão 1)

In [102]:
np.random.randn(3, 3)

array([[ 2.34918265, -0.30878651, -0.19838179],
       [-0.78244798, -0.35876837, -0.18244444],
       [ 0.95050639, -0.36115315,  0.25320429]])

- Gerando números de uma distribuição uniforme

In [105]:
f = np.random.randint(low=5, high=10, size=(5, 5))
f

array([[6, 6, 5, 6, 7],
       [6, 6, 8, 6, 8],
       [6, 5, 6, 7, 7],
       [8, 7, 6, 7, 6],
       [5, 8, 7, 6, 8]])