In [29]:
import numpy as np

# Entrada e saída
- NumPy oferece algumas maneiras de realizar I/O

## Salvando e carregando arrays
- Você pode salvar um dado array utilizando a função `savez()`

In [30]:
x = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])
y = np.array([10, 20, 30, 40, 50, 60])

In [31]:
np.savez("meus_arrays.npz", x=x, y=y)

- Para carregar os arrays salvos, podemos usar o método `load()`

In [32]:
ma = np.load("meus_arrays.npz")
ma

In [33]:
ma["x"]

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [34]:
ma["y"]

array([10, 20, 30, 40, 50, 60])

## Salvando usando Pickle
- Uma outra maneira interessante de guardar arrays do numpy (e em python em geral) é usando a biblioteca [pickle](https://docs.python.org/3/library/pickle.html)

In [35]:
import pickle

In [37]:
A = np.random.rand(20, 20)
A

array([[0.30202354, 0.47924456, 0.95624743, 0.2622545 , 0.13586204,
        0.39163808, 0.82467898, 0.73782324, 0.65264588, 0.81307199,
        0.60703899, 0.81830432, 0.46356536, 0.6786889 , 0.19311954,
        0.81011295, 0.45517576, 0.67174421, 0.85801024, 0.75071475],
       [0.33538316, 0.4714935 , 0.22502239, 0.6182492 , 0.94905878,
        0.56591365, 0.78124148, 0.30496999, 0.15306107, 0.91273559,
        0.03688781, 0.88768771, 0.17345597, 0.60540992, 0.55111573,
        0.36137756, 0.12143306, 0.59732292, 0.40023364, 0.34088631],
       [0.28586381, 0.96541328, 0.03737024, 0.13610974, 0.263928  ,
        0.18703459, 0.78814481, 0.86380702, 0.54105103, 0.64387249,
        0.94659918, 0.65381086, 0.73590339, 0.96448285, 0.09565959,
        0.2978695 , 0.15476811, 0.31536554, 0.81033435, 0.24033447],
       [0.21158452, 0.82736622, 0.12187672, 0.90871106, 0.58978005,
        0.9741406 , 0.82545824, 0.62403445, 0.81407567, 0.25510409,
        0.28846486, 0.83609505, 0.23357832, 0

- Salvando os dados com pickle

In [38]:
with open("A_pickle.pk", "wb") as f:
    pickle.dump(A, f)

- Carregando dados de um pickle

In [39]:
A_ = np.load("A_pickle.pk", allow_pickle=True)
A_.shape

(20, 20)

In [40]:
A

array([[0.30202354, 0.47924456, 0.95624743, 0.2622545 , 0.13586204,
        0.39163808, 0.82467898, 0.73782324, 0.65264588, 0.81307199,
        0.60703899, 0.81830432, 0.46356536, 0.6786889 , 0.19311954,
        0.81011295, 0.45517576, 0.67174421, 0.85801024, 0.75071475],
       [0.33538316, 0.4714935 , 0.22502239, 0.6182492 , 0.94905878,
        0.56591365, 0.78124148, 0.30496999, 0.15306107, 0.91273559,
        0.03688781, 0.88768771, 0.17345597, 0.60540992, 0.55111573,
        0.36137756, 0.12143306, 0.59732292, 0.40023364, 0.34088631],
       [0.28586381, 0.96541328, 0.03737024, 0.13610974, 0.263928  ,
        0.18703459, 0.78814481, 0.86380702, 0.54105103, 0.64387249,
        0.94659918, 0.65381086, 0.73590339, 0.96448285, 0.09565959,
        0.2978695 , 0.15476811, 0.31536554, 0.81033435, 0.24033447],
       [0.21158452, 0.82736622, 0.12187672, 0.90871106, 0.58978005,
        0.9741406 , 0.82545824, 0.62403445, 0.81407567, 0.25510409,
        0.28846486, 0.83609505, 0.23357832, 0

## Salvando usando `np.savetxt`
- Por fim, uma outra maneira de salvar dados, agora de maneira mais *human-friendly* é usando a função `np.savetxt()`
- Essa função salva dados em arquivos de texto (txt file)

In [41]:
np.savetxt("dados.csv", A, delimiter=",", fmt='%.3f')

- Para carregar esses dados, vamos usar a função `np.genfromtxt` 

In [42]:
dados = np.genfromtxt('dados.csv', delimiter=',')
dados.shape

(20, 20)

In [43]:
dados

array([[0.302, 0.479, 0.956, 0.262, 0.136, 0.392, 0.825, 0.738, 0.653,
        0.813, 0.607, 0.818, 0.464, 0.679, 0.193, 0.81 , 0.455, 0.672,
        0.858, 0.751],
       [0.335, 0.471, 0.225, 0.618, 0.949, 0.566, 0.781, 0.305, 0.153,
        0.913, 0.037, 0.888, 0.173, 0.605, 0.551, 0.361, 0.121, 0.597,
        0.4  , 0.341],
       [0.286, 0.965, 0.037, 0.136, 0.264, 0.187, 0.788, 0.864, 0.541,
        0.644, 0.947, 0.654, 0.736, 0.964, 0.096, 0.298, 0.155, 0.315,
        0.81 , 0.24 ],
       [0.212, 0.827, 0.122, 0.909, 0.59 , 0.974, 0.825, 0.624, 0.814,
        0.255, 0.288, 0.836, 0.234, 0.563, 0.197, 0.808, 0.571, 0.359,
        0.976, 0.266],
       [0.505, 0.997, 0.921, 0.35 , 0.084, 0.113, 0.872, 0.759, 0.112,
        0.818, 0.235, 0.668, 0.053, 0.502, 0.514, 0.617, 0.583, 0.054,
        0.565, 0.738],
       [0.553, 0.19 , 0.763, 0.506, 0.495, 0.746, 0.553, 0.95 , 0.455,
        0.516, 0.817, 0.277, 0.27 , 0.825, 0.796, 0.56 , 0.555, 0.872,
        0.805, 0.672],
       [0.